# Generated by Django 5.0.4 on 2024-04-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
